redis:
  sentinel:
    mastername: airobot
    sentineladdrs:
      - 192.168.6.103:5010
      - 192.168.6.104:5010
      - 192.168.6.105:5010
    password: c7605l0Mk0
    db: 10
    dialtimeout: 5s
    readtimeout: 3s
    writetimeout: 3s

db:
  master:
    dialector: mysql
    username: airobot
    password: i3o3aFYUPr
    host: tcp(192.168.6.101:3306)
    path: airobot_dev
    rawquery: charset=utf8&parseTime=True&loc=Local
    maxopen: 100
    maxidle: 10
  slave:
    dialector: mysql
    username: airobot
    password: i3o3aFYUPr
    host: tcp(192.168.6.102:3306)
    path: airobot_dev
    rawquery: charset=utf8&parseTime=True&loc=Local
    maxopen: 100
    maxidle: 10

rabbitmq:
  service: 192.168.6.100:6001
  host: airobot-dev
  username: airobot
  password: tbgmJIUoHx

mqtt:
  services:
    - tcp://192.168.6.100:4001
  username: airobot
  password: GCpm4WZCBB
  clientid: airobot-bizcore
