db:
  master:
    dialector: sqlite
    path: test_db.db

#    dialector: sqlserver
#    username: sa
#    password: 123456
#    host: 127.0.0.1:1433
#    rawquery: database=frontserver

#    dialector: mysql
#    username: airobot
#    password: i3o3aFYUPr
#    host: 192.168.6.101:3306
#    path: airobot_dev
#    rawquery: charset=utf8&parseTime=True&loc=Local
#    maxopen: 100
#    maxidle: 10
#  slave:
#    dialector: mysql
#    username: airobot
#    password: i3o3aFYUPr
#    host: 192.168.6.102:3306
#    path: airobot_dev
#    rawquery: charset=utf8&parseTime=True&loc=Local
#    maxopen: 100
#    maxidle: 10
