// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package utils

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD579c6ceDecodeGitWanpinghuiComWPHGoCommonWph(in *jlexer.Lexer, out *ResHead) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "code":
			out.Code = int(in.Int())
		case "msg":
			out.Msg = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD579c6ceEncodeGitWanpinghuiComWPHGoCommonWph(out *jwriter.Writer, in ResHead) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	if in.Msg != "" {
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ResHead) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD579c6ceEncodeGitWanpinghuiComWPHGoCommonWph(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ResHead) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD579c6ceEncodeGitWanpinghuiComWPHGoCommonWph(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ResHead) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD579c6ceDecodeGitWanpinghuiComWPHGoCommonWph(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ResHead) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD579c6ceDecodeGitWanpinghuiComWPHGoCommonWph(l, v)
}
func easyjsonD579c6ceDecodeGitWanpinghuiComWPHGoCommonWph1(in *jlexer.Lexer, out *Res) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "body":
			if m, ok := out.Body.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.Body.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.Body = in.Interface()
			}
		case "code":
			out.Code = int(in.Int())
		case "msg":
			out.Msg = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD579c6ceEncodeGitWanpinghuiComWPHGoCommonWph1(out *jwriter.Writer, in Res) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Body != nil {
		const prefix string = ",\"body\":"
		first = false
		out.RawString(prefix[1:])
		if m, ok := in.Body.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.Body.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.Body))
		}
	}
	{
		const prefix string = ",\"code\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Code))
	}
	if in.Msg != "" {
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Msg))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Res) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD579c6ceEncodeGitWanpinghuiComWPHGoCommonWph1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Res) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD579c6ceEncodeGitWanpinghuiComWPHGoCommonWph1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Res) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD579c6ceDecodeGitWanpinghuiComWPHGoCommonWph1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Res) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD579c6ceDecodeGitWanpinghuiComWPHGoCommonWph1(l, v)
}
func easyjsonD579c6ceDecodeGitWanpinghuiComWPHGoCommonWph2(in *jlexer.Lexer, out *RequestPromise) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD579c6ceEncodeGitWanpinghuiComWPHGoCommonWph2(out *jwriter.Writer, in RequestPromise) {
	out.RawByte('{')
	first := true
	_ = first
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RequestPromise) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD579c6ceEncodeGitWanpinghuiComWPHGoCommonWph2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RequestPromise) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD579c6ceEncodeGitWanpinghuiComWPHGoCommonWph2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RequestPromise) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD579c6ceDecodeGitWanpinghuiComWPHGoCommonWph2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RequestPromise) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD579c6ceDecodeGitWanpinghuiComWPHGoCommonWph2(l, v)
}
