project:
  name: &projectName epshealth-airobot-monitor
  port: 8090
  swagger: true

relatedserver:
  dispatch: http://epshealth-airobot-dispatch:8090

jwt:
  issuer: *projectName
  secret: c2VybmFtZSI6InRlc3QiLCJleHAiOjE2MDA5MjE0MjEsImlzcyI6ImVwc2hlYWx0aCIsIm5iZiI6MTYwMDkxNDIyMX0
  expires: 1440m

redis:
  sentinel:
    mastername: airobot
    sentineladdrs:
      - 192.168.6.203:5010
      - 192.168.6.204:5010
      - 192.168.6.205:5010
    password: c7605l0Mk0
    db: 10

db:
  master:
    dialector: mysql
    username: airobot
    password: Airobot&test3
    host: tcp(192.168.6.201:3306)
    path: airobot_dev
    rawquery: charset=utf8&parseTime=True&loc=Local
    maxopen: 100
    maxidle: 10
  slave:
    dialector: mysql
    username: airobot
    password: Airobot&test3
    host: tcp(192.168.6.202:3306)
    path: airobot_dev
    rawquery: charset=utf8&parseTime=True&loc=Local
    maxopen: 100
    maxidle: 10

rabbitmq:
  service: 192.168.6.120:6001
  host: airobot
  username: airobot
  password: Airobot&test5

log:
  project: *projectName
  author: ycm
  machine: machine_ycm
  level: debug
  jsonFormat: true
  file: /var/log/airobot/monitor.log

mqtt:
  services:
    - 192.168.6.120:4001
  username: airobot
  password: Airobot@test3
  clientid: monitor-clientId

elastic:
  hosts:
    - http://192.168.6.120:7001
  username: airobot
  password: Airobot@elastic5
